### ISSUE TITLE
Naming the IDE

### ISSUE THREAD

**Issue by JuanchiRios** [thin-languages/slimdown#1]
I Thought few names like:
-  Ide Less: Which respect the naming consistency in other project like java-less, lambda-less,etc.
- Thin-ide: Because it's sounds fine with Thin-Languages and i relate to scala-ide

Well we can play with the words: IDE, Thin, less and something funky will come to us eventually.

**Comment by micaelafmartino** [comment]
I'm very bad at this :stuck_out_tongue_closed_eyes: 

@bossiernesto @nscarcella you named the other projects.. any ideas?

**Comment by iluetich** [comment]
Just some thoughts:
- **Slimdown** (as an action to be thinner, to lose weight)
- **nameLess** (because reasons)

**Comment by nscarcella** [comment]
Haha, I like where this is going

**Comment by micaelafmartino** [comment]
I just left [this](http://doodle.com/poll/spykrk5dehtukpmf5hqd8dk2/admin#table) here to make it easier to pick one..

**Comment by JuanchiRios** [comment]
Taking a shower a ThinLanguage's slogan came into my head
_Keep ideas, not code_

I like **Nameless** because one thing that happens in Thin is that we are in someway syntax independent. And without syntax you just don't know how to write things(of course we do because we have good defaults). So if you don't know how to write your ideas, how we are name the ide. Nameless represent that idea and is kind of funny :+1: 

Also we could name it **Syntaxless** but Thin is be way above than writing code with your favourite syntax

**Comment by bossiernesto** [comment]
I like the idea of naming Slimdown or ThinIDE,  i don't have any strong reason of  why i should not consider Syntaxless or Nameless to name the IDE. I like the idea of naming it Slimdown because it relates with our idea of removing the syntax fat.

**Comment by micaelafmartino** [comment]
Well, looking the doodle results and the comments here, it seems we have a winner. 
It will be Silmdown.

If anyone have any objections, feel free to reopen :stuck_out_tongue:
