### ISSUE TITLE
Sbt configuration needs fix

### ISSUE THREAD

**Issue by JuanchiRios** [thin-languages/slimdown#3]
Running sbt eclipse create 6 source folders
- src/main/scala-2.11
- src/test/scala-2.11
- src/main/scala
- src/test/scala
- src/main/java
- src/test/java

It's bothers because appears in the package explorer in eclipse. I had this problem before and i couldn't fix it. If anyone know, i'd appreciate it.

**Comment by micaelafmartino** [comment]
I had the same problem before, and found two ways to generate correctly the scala-project structure:
- Download a [complete archtype catalog](https://github.com/thin-languages/Thin-IDE/files/165400/archetype-catalog.zip), paste it in your $M2_HOME and select a scala archtype (e.g. scala-archetype-simple)

``` shell
mvn archetype:generate \
    -DarchetypeCatalog=local \
    -DarchetypeGroupId=net.alchim31.maven 
    -DarchetypeArtifactId=scala-archetype-simple
#if the third parameter is omitted, maven shows all the posible archtypes in the catalog.
```
- If you 're under *nix, you could use [giter8 templates](https://github.com/n8han/giter8/wiki/giter8-templates)

**Comment by JuanchiRios** [comment]
Hi @matiasfmartino , i tried what you told me and failed. But i found that if you add this two lines in the project.sbt the problem is solved
1. unmanagedSourceDirectories in Compile := (scalaSource in Compile).value :: Nil  
2. unmanagedSourceDirectories in Test := (scalaSource in Test).value :: Nil

I will make a PR closing the issue
